name: docker_pull_and_run

on:
  workflow_dispatch:

jobs:
  pull_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Pull docker image
        run: docker pull hello-world
      - name: Run docker image
        run: docker run hello-world

