name: run go app with using matrix

on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  Hello:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go_versions: [1.18,1.19.1,1.19.2]
    
    runs-on: ${{ matrix.platform}}

    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go_versions}}
          
      - uses: actions/checkout@v3

      - name: Run go file
        run: go run main.go

