name: go hello world 

# on: 
#   push:
#     branches:
#       - master

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


jobs:
  Hello:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.platform}}

    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
          
      - uses: actions/checkout@v3

      - name: Run go file
        run: go run main.go

      # - name: Build
      #   run: go build -v ./...

      # - name: Test
      #   run: go test -v ./...
      
      
