name: hello world 

on: 
  push:
    branches:
      - master

jobs:
  Hello:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.platform}}

    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14.1"
          
      - uses: actions/checkout@v2

      - name: Run go file
        run: go run main.go
      
